
on:
  push:
    branches: [ "master" ]
name : deploy api on push
jobs:
  web-deploy:
    name : auto deploy
    runs-on: ubuntu-latest
    steps:
        - name: get lastest code
          uses: actions/checkout@v3

        - name: deploys
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            protocol: ftps
            port: ${{ secrets.FTP_PORT }}
            exclude : .git*
              - .git*/**
              - .github
